### ISSUE TITLE
Documents

### ISSUE THREAD

**Issue by kimbob138** [edumorlom/moms-infants-healthy#500] opened 2022-07-10 19:02 UTC
Once a document has been uploaded, there is no option to delete or rename it. 

![IMG_D71DB3D964BB-1](https://user-images.githubusercontent.com/97994738/178158436-29072bee-1f4d-4669-a23c-2cf30b9d2e23.jpeg)

**Comment by gabegomez000** [comment] 2022-07-26 22:45
Closing this issue as it is a duplicate of Issue #406

**Closed as not planned by gabegomez000** 2022-07-26 22:45 UTC
Labels: duplicate
