### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by jenni20000** [edumorlom/moms-infants-healthy#435] opened 2022-03-29 00:56 UTC
The checklist under apply to WIC isn't working. The user cannot check anything off.
![IMG_4320](https://user-images.githubusercontent.com/93234273/160511155-e24f0d84-45ab-4226-b52a-5675372b4621.jpeg)

**Comment by julianlopez6850** [comment] 2022-03-29 02:05
@jenni20000 
I believe this issue was fixed by PR ##363, which fixed the same issue, posted as issue #354.

I believe you may be testing an old version of the development branch. You need to do the command `git pull` in your local repository in order to get the updates that have been made to the branch whenever changes are made.

Please let me know if this works and the issue is fixed on your end. Thanks.

**Comment by jenni20000** [comment] 2022-04-05 00:40
@julianlopez6850 
You're right that fixes it, thanks!

**Closed as completed** 2022-04-05 00:40 UTC
Labels: duplicate
